name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup .NET 6 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and publish Docker image
        run: |
          docker build -t public.ecr.aws/u3q3l1u9/library:${{ github.sha }} .
          docker login -u AWS -p $(aws ecr get-login-password --region us-east-1) public.ecr.aws/u3q3l1u9/library
          docker push public.ecr.aws/u3q3l1u9/library:${{ github.sha }}
      - name: SSH into EC2 instance and deploy Docker image
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 54.167.156.117
          username: ec2-user
          key: ${{ secrets.DEPLOYMENT_KEY }}
          script: |
            docker stop library-api-app || true
            docker rm library-api-app || true
            docker pull public.ecr.aws/u3q3l1u9/library:${{ github.sha }}
            docker run -d -p 80:80 --name library-api-app public.ecr.aws/u3q3l1u9/library:${{ github.sha }}
